### PR TITLE
Tabs and more

### PR DESCRIPTION
**Pull request by sandervanhooft**
I'll tag you @ciungulete when it's ready - not nearly there yet 😉

### CODE REVIEW

**Comment by sandervanhooft** [comment]
I've filled out some classes, also included a bunch of TODOs.

Main flow:

```php
$tab = $billable->newTab(..)->...->create();
$tab->addItem()->...->create();
$tab->addItem()->...->create();
$tab->addItem()->...->create();
$tab->close();
```

I've dropped scheduling/process_at etc., was overcomplicating things.

@ciungulete Can you check it out and see if you can take it from here?

**Comment by sandervanhooft** [comment]
If not, I'll try to squeeze in some more time tomorrow

**Comment by ciungulete** [comment]
I try to push it forward today.

**Comment by sandervanhooft** [comment]
```php
$billable->newTab()->...->->create();
$tab->addItem()->...->create();
$tab->addItem()->...->create();
$tab->addItem()->...->create();
$tab->close();
```

```php
$billable->newTab()->withItem(function (TabItemBuilder $builder) {
    return $builder...;
})
->withItem()...
->create();
```

**Pull request merged**
